BEGIN {
	printf("/* generated by enum.awk */\n");
	if (mode == "c")
		printf("static const char *%s[] = {\n", name);
	else
		printf("enum %s {\n", name);
}
/^[A-Z_]/ {
	if (mode == "h")
		printf("\t%s_%s,\n", prefix, $1);
	else
		printf("\t\"%s\",\n", $1);
}
END {
	printf("};\n");
}
